name: Web Release

on:
  push:
    branches:  [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Create Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          run: flutter --version
      - name: Get dependencies
        run: flutter pub get

      - name: Analyze project source
        if: success()
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Start Web Release Build
        run: flutter build web
     
      - name: Upload Web Build Files
        uses: actions/upload-artifact@v3
        with:
          name: web-release
          path: ./build/web

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Web Release
      uses: actions/download-artifact@v2
      with:
        name: web-release

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./